### ISSUE TITLE
Remove toolbar icon

### ISSUE THREAD

**Issue by JackNUMBER** [Qwant/QwantLiteExtension#1]
Hi, the icon in the toolbar is useless. Is it possible to remove it?
In this way the add-on is like other search engine add-ons.

**Comment by Pierohub** [comment]
Hi! Thank you for your feedback.
Indeed, this icon is useless, I'm going to remove it.

**Comment by Pierohub** [comment]
Updated: https://addons.mozilla.org/fr/firefox/addon/qwant-lite/versions/?page=1#version-1.0.5
