### ISSUE TITLE
Enter key in address bar stops working 

### ISSUE THREAD

**Issue by michaelclassen** [Qwant/QwantLiteExtension#3]
After a couple of searches the enter key stops working in the address bar (Ctrl+L), i.e. triggers no action anymore in FF 60.3.0esr 64 bit. This does not seem to happen on 32 bit.

**Comment by Pierohub** [comment]
Hi @michaelclassen this issue is relative to the browser and not the extension.
You should report it on Bugzilla https://bugzilla.mozilla.org/
Thanks
