### ISSUE TITLE
The extension has limitation with only search with default settings

### ISSUE THREAD

**Issue by PoundXI** [Qwant/QwantLiteExtension#4]
The extension should search with user settings.

eg. language, safe search level and open links in new tab.

I also fork this repository and add **search-with-settings** features.

You can check it here:
[https://github.com/PoundXI/QwantLiteExtension/tree/search-with-settings](https://github.com/PoundXI/QwantLiteExtension/tree/search-with-settings)

If you interest it. you can create a new branch and I will create a pull request for you.

Thank you.

**Comment by Pierohub** [comment]
Hi @PoundXI ,
Thank you for your recommandation, it's a cool idea.
I tried to setup the extension on Firefox and Brave, and the settings seem to not be saved.
I think it's because Qwant Lite has a new version, what do you think?

**Comment by PoundXI** [comment]
Yes, Qwant setting behavior has changed. Previously we can detect saving state with "si" param. But now no "si" param appear in url when user saving.

This idea still possible with some code changes.

**Comment by xfim** [comment]
Dear all,

How is the status of this issue? Is it possible to make qwant lite search within user settings? I am quite happy with qwant, but definitively would like the default search bar to behave within my settings.

Thank you.

**Comment by rloutrel** [comment]
I guess it would be a different approach (and I do not know if possible), but could it as default use browser settings to add query parameters like:
if dark theme is used => search_url += "&theme=1" (similar for location and language)

It could be modified/overwritten/configured like plugins (if firefox allows such solution)

**Comment by raed667** [comment]
If you update to the latest version `1.0.8` settings are now saved and applied for the following searches: https://addons.mozilla.org/en-US/firefox/addon/qwant-lite/

Don't hesitate to open another issue if you encounter any problem!

**Comment by rloutrel** [comment]
Love it! Thank you!
This and the fact, that the page is incredibly faster than earlier: default search engine changed from duckduckgo to Qwant!

Bravo les gars! vous pouvez allez profiter de la plage nicoise, par ce temps, maintenant!
