### ISSUE TITLE
Firefox add-on doesn't save my settings?

### ISSUE THREAD

**Issue by felleg** [Qwant/QwantLiteExtension#8]
When I try to change my theme to dark, it seems the settings don't apply to any new tab. Is this a bug?
Using version 1.0.7

**Comment by raed667** [comment]
Indeed, saving settings was not supported until #6 for Firefox and #7 for Chromium.

Should be released to the different extension stores in the next couple of days.

**Comment by raed667** [comment]
If you update to the latest version `1.0.8` settings are now saved: https://addons.mozilla.org/en-US/firefox/addon/qwant-lite/

Don't hesitate to open another issue if you encounter any problem!
